language: java

sudo: false

jdk:
  - oraclejdk8

script:
  - chmod a+x ./.BuildScripts/build.sh
  - ./.BuildScripts/build.sh

after_success:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)
