package reference;
import gov.nasa.jpf.annotation.Conditional;
import gov.nasa.jpf.vm.Verify;

public class RefVarexJ {

	public static void main(String[] args) {
		Verify.resetInstructionCounter();
		new RefVarexJ(Integer.parseInt(args[0]));
	}

	@Conditional public  static boolean a1 = true;
	@Conditional public  static boolean a2 = true;
	@Conditional public  static boolean a3 = true;
	@Conditional public  static boolean a4 = true;
	@Conditional public  static boolean a5 = true;
	@Conditional public  static boolean a6 = true;
	@Conditional public  static boolean a7 = true;
	@Conditional public  static boolean a8 = true;
	@Conditional public  static boolean a9 = true;
	@Conditional public  static boolean a10 = true;
	@Conditional public  static boolean a11 = true;
	@Conditional public  static boolean a12 = true;
	@Conditional public  static boolean a13 = true;
	@Conditional public  static boolean a14 = true;
	@Conditional public  static boolean a15 = true;
	@Conditional public  static boolean a16 = true;
	@Conditional public  static boolean a17 = true;
	@Conditional public  static boolean a18 = true;
	@Conditional public  static boolean a19 = true;
	@Conditional public  static boolean a20 = true;
	@Conditional public  static boolean a21 = true;
	@Conditional public  static boolean a22 = true;
	@Conditional public  static boolean a23 = true;
	@Conditional public  static boolean a24 = true;
	@Conditional public  static boolean a25 = true;
	@Conditional public  static boolean a26 = true;
	@Conditional public  static boolean a27 = true;
	@Conditional public  static boolean a28 = true;
	@Conditional public  static boolean a29 = true;
	@Conditional public  static boolean a30 = true;
	@Conditional public  static boolean a31 = true;
	@Conditional public  static boolean a32 = true;
	@Conditional public  static boolean a33 = true;
	@Conditional public  static boolean a34 = true;
	@Conditional public  static boolean a35 = true;
	@Conditional public  static boolean a36 = true;
	@Conditional public  static boolean a37 = true;
	@Conditional public  static boolean a38 = true;
	@Conditional public  static boolean a39 = true;
	@Conditional public  static boolean a40 = true;
	@Conditional public  static boolean a41 = true;
	@Conditional public  static boolean a42 = true;
	@Conditional public  static boolean a43 = true;
	@Conditional public  static boolean a44 = true;
	@Conditional public  static boolean a45 = true;
	@Conditional public  static boolean a46 = true;
	@Conditional public  static boolean a47 = true;
	@Conditional public  static boolean a48 = true;
	@Conditional public  static boolean a49 = true;
	@Conditional public  static boolean a50 = true;
	@Conditional public  static boolean a51 = true;
	@Conditional public  static boolean a52 = true;
	@Conditional public  static boolean a53 = true;
	@Conditional public  static boolean a54 = true;
	@Conditional public  static boolean a55 = true;
	@Conditional public  static boolean a56 = true;
	@Conditional public  static boolean a57 = true;
	@Conditional public  static boolean a58 = true;
	@Conditional public  static boolean a59 = true;
	@Conditional public  static boolean a60 = true;
	@Conditional public  static boolean a61 = true;
	@Conditional public  static boolean a62 = true;
	@Conditional public  static boolean a63 = true;
	@Conditional public  static boolean a64 = true;
	@Conditional public  static boolean a65 = true;
	@Conditional public  static boolean a66 = true;
	@Conditional public  static boolean a67 = true;
	@Conditional public  static boolean a68 = true;
	@Conditional public  static boolean a69 = true;
	@Conditional public  static boolean a70 = true;
	@Conditional public  static boolean a71 = true;
	@Conditional public  static boolean a72 = true;
	@Conditional public  static boolean a73 = true;
	@Conditional public  static boolean a74 = true;
	@Conditional public  static boolean a75 = true;
	@Conditional public  static boolean a76 = true;
	@Conditional public  static boolean a77 = true;
	@Conditional public  static boolean a78 = true;
	@Conditional public  static boolean a79 = true;
	@Conditional public  static boolean a80 = true;
	@Conditional public  static boolean a81 = true;
	@Conditional public  static boolean a82 = true;
	@Conditional public  static boolean a83 = true;
	@Conditional public  static boolean a84 = true;
	@Conditional public  static boolean a85 = true;
	@Conditional public  static boolean a86 = true;
	@Conditional public  static boolean a87 = true;
	@Conditional public  static boolean a88 = true;
	@Conditional public  static boolean a89 = true;
	@Conditional public  static boolean a90 = true;
	@Conditional public  static boolean a91 = true;
	@Conditional public  static boolean a92 = true;
	@Conditional public  static boolean a93 = true;
	@Conditional public  static boolean a94 = true;
	@Conditional public  static boolean a95 = true;
	@Conditional public  static boolean a96 = true;
	@Conditional public  static boolean a97 = true;
	@Conditional public  static boolean a98 = true;
	@Conditional public  static boolean a99 = true;
	@Conditional public  static boolean a100 = true;
	
	int i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i13, i14, i15, i16, i17, i18, i19, i20, i21, i22, i23, i24, i25, i26, i27, i28, i29, i30, i31, i32, i33, i34, i35, i36, i37, i38, i39, i40,
			i41, i42, i43, i44, i45, i46, i47, i48, i49, i50, i51, i52, i53, i54, i55, i56, i57, i58, i59, i60, i61, i62, i63, i64, i65, i66, i67, i68, i69, i70, i71, i72, i73, i74, i75, i76, i77,
			i78, i79, i80, i81, i82, i83, i84, i85, i86, i87, i88, i89, i90, i91, i92, i93, i94, i95, i96, i97, i98, i99, i100;
	public RefVarexJ(int max) {
		int i = 0;
		if (i == max) return;
		if (a1) {i1  = 1;} if (++i == max) return;
		if (a2) {i2  = 1;} if (++i == max) return;
		if (a3) {i3  = 1;} if (++i == max) return;
		if (a4) {i4  = 1;} if (++i == max) return;
		if (a5) {i5  = 1;} if (++i == max) return;
		if (a6) {i6  = 1;} if (++i == max) return;
		if (a7) {i7  = 1;} if (++i == max) return;
		if (a8) {i8  = 1;} if (++i == max) return;
		if (a9) {i9  = 1;} if (++i == max) return;
		if (a10){i10 = 1;} if (++i == max) return;
		if (a11){i11 = 1;} if (++i == max) return;
		if (a12){i12 = 1;} if (++i == max) return;
		if (a13){i13 = 1;} if (++i == max) return;
		if (a14){i14 = 1;} if (++i == max) return;
		if (a15){i15 = 1;} if (++i == max) return;
		if (a16){i16 = 1;} if (++i == max) return;
		if (a17){i17 = 1;} if (++i == max) return;
		if (a18){i18 = 1;} if (++i == max) return;
		if (a19){i19 = 1;} if (++i == max) return;
		if (a20){i20 = 1;} if (++i == max) return;
		if (a21){i21 = 1;} if (++i == max) return;
		if (a22){i22 = 1;} if (++i == max) return;
		if (a23){i23 = 1;} if (++i == max) return;
		if (a24){i24 = 1;} if (++i == max) return;
		if (a25){i25 = 1;} if (++i == max) return;
		if (a26){i26 = 1;} if (++i == max) return;
		if (a27){i27 = 1;} if (++i == max) return;
		if (a28){i28 = 1;} if (++i == max) return;
		if (a29){i29 = 1;} if (++i == max) return;
		if (a30){i30 = 1;} if (++i == max) return;
		if (a31){i31  = 1;} if (++i == max) return;
		if (a32){i32  = 1;} if (++i == max) return;
		if (a33){i33  = 1;} if (++i == max) return;
		if (a34){i34  = 1;} if (++i == max) return;
		if (a35){i35  = 1;} if (++i == max) return;
		if (a36){i36  = 1;} if (++i == max) return;
		if (a37){i37  = 1;} if (++i == max) return;
		if (a38){i38  = 1;} if (++i == max) return;
		if (a39){i39  = 1;} if (++i == max) return;
		if (a40){i40  = 1;} if (++i == max) return;
		if (a41){i41  = 1;} if (++i == max) return;
		if (a42){i42  = 1;} if (++i == max) return;
		if (a43){i43  = 1;} if (++i == max) return;
		if (a44){i44  = 1;} if (++i == max) return;
		if (a45){i45  = 1;} if (++i == max) return;
		if (a46){i46  = 1;} if (++i == max) return;
		if (a47){i47  = 1;} if (++i == max) return;
		if (a48){i48  = 1;} if (++i == max) return;
		if (a49){i49  = 1;} if (++i == max) return;
		if (a50){i50  = 1;} if (++i == max) return;
		if (a51){i51  = 1;} if (++i == max) return;
		if (a52){i52  = 1;} if (++i == max) return;
		if (a53){i53  = 1;} if (++i == max) return;
		if (a54){i54  = 1;} if (++i == max) return;
		if (a55){i55  = 1;} if (++i == max) return;
		if (a56){i56  = 1;} if (++i == max) return;
		if (a57){i57  = 1;} if (++i == max) return;
		if (a58){i58  = 1;} if (++i == max) return;
		if (a59){i59  = 1;} if (++i == max) return;
		if (a60){i60  = 1;} if (++i == max) return;
		if (a61) {i61  = 1;} if (++i == max) return;
		if (a62) {i62  = 1;} if (++i == max) return;
		if (a63) {i63  = 1;} if (++i == max) return;
		if (a64) {i64  = 1;} if (++i == max) return;
		if (a65) {i65  = 1;} if (++i == max) return;
		if (a66) {i66  = 1;} if (++i == max) return;
		if (a67) {i67  = 1;} if (++i == max) return;
		if (a68) {i68  = 1;} if (++i == max) return;
		if (a69) {i69  = 1;} if (++i == max) return;
		if (a70){i70  = 1;} if (++i == max) return;
		if (a71){i71  = 1;} if (++i == max) return;
		if (a72){i72  = 1;} if (++i == max) return;
		if (a73){i73  = 1;} if (++i == max) return;
		if (a74){i74  = 1;} if (++i == max) return;
		if (a75){i75  = 1;} if (++i == max) return;
		if (a76){i76  = 1;} if (++i == max) return;
		if (a77){i77  = 1;} if (++i == max) return;
		if (a78){i78  = 1;} if (++i == max) return;
		if (a79){i79  = 1;} if (++i == max) return;
		if (a80){i80  = 1;} if (++i == max) return;
		if (a81){i81  = 1;} if (++i == max) return;
		if (a82){i82  = 1;} if (++i == max) return;
		if (a83){i83  = 1;} if (++i == max) return;
		if (a84){i84  = 1;} if (++i == max) return;
		if (a85){i85  = 1;} if (++i == max) return;
		if (a86){i86  = 1;} if (++i == max) return;
		if (a87){i87  = 1;} if (++i == max) return;
		if (a88){i88  = 1;} if (++i == max) return;
		if (a89){i89  = 1;} if (++i == max) return;
		if (a90){i90  = 1;} if (++i == max) return;
		if (a91){i91  = 1;} if (++i == max) return;
		if (a92){i92  = 1;} if (++i == max) return;
		if (a93){i93  = 1;} if (++i == max) return;
		if (a94){i94  = 1;} if (++i == max) return;
		if (a95){i95  = 1;} if (++i == max) return;
		if (a96){i96  = 1;} if (++i == max) return;
		if (a97){i97  = 1;} if (++i == max) return;
		if (a98){i98  = 1;} if (++i == max) return;
		if (a99){i99  = 1;} if (++i == max) return;
		if (a100){i100 = 1;} if (++i == max) return;
	}
	
}
